<?php

namespace Simp\Core\lib\forms;

use Simp\Core\components\basic_fields\SelectField;
use Simp\Core\modules\config\ConfigManager;
use Simp\Default\DetailWrapperField;
use Simp\Fields\FieldBase;
use Simp\FormBuilder\FormBase;
use Symfony\Component\HttpFoundation\RedirectResponse;

class BasicSettingForm extends FormBase
{

    private bool $validated = true;

    public function getFormId(): string
    {
       return 'basic_setting';
    }

    public function buildForm(array $form): array
    {
        $config = ConfigManager::config()->getConfigFile('basic.site.setting');
        $form['site'] = [
            'type' => 'details',
            'label' => 'Site details',
            'name' => 'site',
            'id' => 'site',
            'class' => ['form-details'],
            'handler' => DetailWrapperField::class,
            'inner_field' => [
                'site_name' => [
                    'label' => 'Site name',
                    'type' => 'text',
                    'required' => true,
                    'name' => 'site_name',
                    'id' => 'site_name',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('site_name'),
                ],
                'site_phone' => [
                    'label' => 'Site phone',
                    'type' => 'tel',
                    'required' => true,
                    'name' => 'site_phone',
                    'id' => 'site_phone',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('site_phone'),
                ],
                'site_address' => [
                    'label' => 'Site address',
                    'type' => 'text',
                    'required' => true,
                    'name' => 'site_address',
                    'id' => 'site_address',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('site_address'),
                ],
                'site_postal_code' => [
                    'label' => 'Site Postal Code',
                    'type' => 'text',
                    'required' => true,
                    'name' => 'site_postal_code',
                    'id' => 'site_postal_code',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('site_postal_code'),
                ],
                'site_locality' => [
                    'label' => 'Site Locality',
                    'type' => 'text',
                    'required' => true,
                    'name' => 'site_locality',
                    'id' => 'site_locality',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('site_locality'),
                ],
                'site_country' => [
                    'label' => 'Site Country',
                    'type' => 'select',
                    'required' => true,
                    'name' => 'site_country',
                    'id' => 'site_country',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('site_country'),
                    'handler' => SelectField::class,
                    'option_values' => [
                        'AF' => 'Afghanistan',
                        'AX' => 'Åland Islands',
                        'AL' => 'Albania',
                        'DZ' => 'Algeria',
                        'AS' => 'American Samoa',
                        'AD' => 'Andorra',
                        'AO' => 'Angola',
                        'AI' => 'Anguilla',
                        'AQ' => 'Antarctica',
                        'AG' => 'Antigua and Barbuda',
                        'AR' => 'Argentina',
                        'AM' => 'Armenia',
                        'AW' => 'Aruba',
                        'AU' => 'Australia',
                        'AT' => 'Austria',
                        'AZ' => 'Azerbaijan',
                        'BS' => 'Bahamas',
                        'BH' => 'Bahrain',
                        'BD' => 'Bangladesh',
                        'BB' => 'Barbados',
                        'BY' => 'Belarus',
                        'BE' => 'Belgium',
                        'BZ' => 'Belize',
                        'BJ' => 'Benin',
                        'BM' => 'Bermuda',
                        'BT' => 'Bhutan',
                        'BO' => 'Bolivia',
                        'BQ' => 'Bonaire, Sint Eustatius and Saba',
                        'BA' => 'Bosnia and Herzegovina',
                        'BW' => 'Botswana',
                        'BV' => 'Bouvet Island',
                        'BR' => 'Brazil',
                        'IO' => 'British Indian Ocean Territory',
                        'BN' => 'Brunei Darussalam',
                        'BG' => 'Bulgaria',
                        'BF' => 'Burkina Faso',
                        'BI' => 'Burundi',
                        'CV' => 'Cabo Verde',
                        'KH' => 'Cambodia',
                        'CM' => 'Cameroon',
                        'CA' => 'Canada',
                        'KY' => 'Cayman Islands',
                        'CF' => 'Central African Republic',
                        'TD' => 'Chad',
                        'CL' => 'Chile',
                        'CN' => 'China',
                        'CX' => 'Christmas Island',
                        'CC' => 'Cocos (Keeling) Islands',
                        'CO' => 'Colombia',
                        'KM' => 'Comoros',
                        'CG' => 'Congo',
                        'CD' => 'Congo (Democratic Republic)',
                        'CK' => 'Cook Islands',
                        'CR' => 'Costa Rica',
                        'CI' => 'Côte d\'Ivoire',
                        'HR' => 'Croatia',
                        'CU' => 'Cuba',
                        'CW' => 'Curaçao',
                        'CY' => 'Cyprus',
                        'CZ' => 'Czechia',
                        'DK' => 'Denmark',
                        'DJ' => 'Djibouti',
                        'DM' => 'Dominica',
                        'DO' => 'Dominican Republic',
                        'EC' => 'Ecuador',
                        'EG' => 'Egypt',
                        'SV' => 'El Salvador',
                        'GQ' => 'Equatorial Guinea',
                        'ER' => 'Eritrea',
                        'EE' => 'Estonia',
                        'SZ' => 'Eswatini',
                        'ET' => 'Ethiopia',
                        'FK' => 'Falkland Islands',
                        'FO' => 'Faroe Islands',
                        'FJ' => 'Fiji',
                        'FI' => 'Finland',
                        'FR' => 'France',
                        'GF' => 'French Guiana',
                        'PF' => 'French Polynesia',
                        'TF' => 'French Southern Territories',
                        'GA' => 'Gabon',
                        'GM' => 'Gambia',
                        'GE' => 'Georgia',
                        'DE' => 'Germany',
                        'GH' => 'Ghana',
                        'GI' => 'Gibraltar',
                        'GR' => 'Greece',
                        'GL' => 'Greenland',
                        'GD' => 'Grenada',
                        'GP' => 'Guadeloupe',
                        'GU' => 'Guam',
                        'GT' => 'Guatemala',
                        'GG' => 'Guernsey',
                        'GN' => 'Guinea',
                        'GW' => 'Guinea-Bissau',
                        'GY' => 'Guyana',
                        'HT' => 'Haiti',
                        'HM' => 'Heard Island and McDonald Islands',
                        'VA' => 'Holy See',
                        'HN' => 'Honduras',
                        'HK' => 'Hong Kong',
                        'HU' => 'Hungary',
                        'IS' => 'Iceland',
                        'IN' => 'India',
                        'ID' => 'Indonesia',
                        'IR' => 'Iran',
                        'IQ' => 'Iraq',
                        'IE' => 'Ireland',
                        'IM' => 'Isle of Man',
                        'IL' => 'Israel',
                        'IT' => 'Italy',
                        'JM' => 'Jamaica',
                        'JP' => 'Japan',
                        'JE' => 'Jersey',
                        'JO' => 'Jordan',
                        'KZ' => 'Kazakhstan',
                        'KE' => 'Kenya',
                        'KI' => 'Kiribati',
                        'KP' => 'North Korea',
                        'KR' => 'South Korea',
                        'KW' => 'Kuwait',
                        'KG' => 'Kyrgyzstan',
                        'LA' => "Lao People's Democratic Republic",
                        'LV' => 'Latvia',
                        'LB' => 'Lebanon',
                        'LS' => 'Lesotho',
                        'LR' => 'Liberia',
                        'LY' => 'Libya',
                        'LI' => 'Liechtenstein',
                        'LT' => 'Lithuania',
                        'LU' => 'Luxembourg',
                        'MO' => 'Macao',
                        'MG' => 'Madagascar',
                        'MW' => 'Malawi',
                        'MY' => 'Malaysia',
                        'MV' => 'Maldives',
                        'ML' => 'Mali',
                        'MT' => 'Malta',
                        'MH' => 'Marshall Islands',
                        'MQ' => 'Martinique',
                        'MR' => 'Mauritania',
                        'MU' => 'Mauritius',
                        'YT' => 'Mayotte',
                        'MX' => 'Mexico',
                        'FM' => 'Micronesia',
                        'MD' => 'Moldova',
                        'MC' => 'Monaco',
                        'MN' => 'Mongolia',
                        'ME' => 'Montenegro',
                        'MS' => 'Montserrat',
                        'MA' => 'Morocco',
                        'MZ' => 'Mozambique',
                        'MM' => 'Myanmar',
                        'NA' => 'Namibia',
                        'NR' => 'Nauru',
                        'NP' => 'Nepal',
                        'NL' => 'Netherlands',
                        'NC' => 'New Caledonia',
                        'NZ' => 'New Zealand',
                        'NI' => 'Nicaragua',
                        'NE' => 'Niger',
                        'NG' => 'Nigeria',
                        'NU' => 'Niue',
                        'NF' => 'Norfolk Island',
                        'MK' => 'North Macedonia',
                        'MP' => 'Northern Mariana Islands',
                        'NO' => 'Norway',
                        'OM' => 'Oman',
                        'PK' => 'Pakistan',
                        'PW' => 'Palau',
                        'PS' => 'Palestine, State of',
                        'PA' => 'Panama',
                        'PG' => 'Papua New Guinea',
                        'PY' => 'Paraguay',
                        'PE' => 'Peru',
                        'PH' => 'Philippines',
                        'PN' => 'Pitcairn',
                        'PL' => 'Poland',
                        'PT' => 'Portugal',
                        'PR' => 'Puerto Rico',
                        'QA' => 'Qatar',
                        'RE' => 'Réunion',
                        'RO' => 'Romania',
                        'RU' => 'Russian Federation',
                        'RW' => 'Rwanda',
                        'BL' => 'Saint Barthélemy',
                        'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
                        'KN' => 'Saint Kitts and Nevis',
                        'LC' => 'Saint Lucia',
                        'MF' => 'Saint Martin (French part)',
                        'PM' => 'Saint Pierre and Miquelon',
                        'VC' => 'Saint Vincent and the Grenadines',
                        'WS' => 'Samoa',
                        'SM' => 'San Marino',
                        'ST' => 'Sao Tome and Principe',
                        'SA' => 'Saudi Arabia',
                        'SN' => 'Senegal',
                        'RS' => 'Serbia',
                        'SC' => 'Seychelles',
                        'SL' => 'Sierra Leone',
                        'SG' => 'Singapore',
                        'SX' => 'Sint Maarten (Dutch part)',
                        'SK' => 'Slovakia',
                        'SI' => 'Slovenia',
                        'SB' => 'Solomon Islands',
                        'SO' => 'Somalia',
                        'ZA' => 'South Africa',
                        'GS' => 'South Georgia and the South Sandwich Islands',
                        'SS' => 'South Sudan',
                        'ES' => 'Spain',
                        'LK' => 'Sri Lanka',
                        'SD' => 'Sudan',
                        'SR' => 'Suriname',
                        'SJ' => 'Svalbard and Jan Mayen',
                        'SE' => 'Sweden',
                        'CH' => 'Switzerland',
                        'SY' => 'Syrian Arab Republic',
                        'TW' => 'Taiwan',
                        'TJ' => 'Tajikistan',
                        'TZ' => 'Tanzania',
                        'TH' => 'Thailand',
                        'TL' => 'Timor-Leste',
                        'TG' => 'Togo',
                        'TK' => 'Tokelau',
                        'TO' => 'Tonga',
                        'TT' => 'Trinidad and Tobago',
                        'TN' => 'Tunisia',
                        'TR' => 'Türkiye',
                        'TM' => 'Turkmenistan',
                        'TC' => 'Turks and Caicos Islands',
                        'TV' => 'Tuvalu',
                        'UG' => 'Uganda',
                        'UA' => 'Ukraine',
                        'AE' => 'United Arab Emirates',
                        'GB' => 'United Kingdom',
                        'US' => 'United States',
                        'UM' => 'United States Minor Outlying Islands',
                        'UY' => 'Uruguay',
                        'UZ' => 'Uzbekistan',
                        'VU' => 'Vanuatu',
                        'VE' => 'Venezuela',
                        'VN' => 'Viet Nam',
                        'VG' => 'Virgin Islands (British)',
                        'VI' => 'Virgin Islands (U.S.)',
                        'WF' => 'Wallis and Futuna',
                        'EH' => 'Western Sahara',
                        'YE' => 'Yemen',
                        'ZM' => 'Zambia',
                        'ZW' => 'Zimbabwe',
                    ]
                ],
                'site_slogan' => [
                    'label' => 'Site slogan',
                    'type' => 'text',
                    'required' => true,
                    'name' => 'site_slogan',
                    'id' => 'site_slogan',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('site_slogan'),
                ],
                'site_email' => [
                    'label' => 'Site email',
                    'type' => 'email',
                    'required' => true,
                    'name' => 'site_email',
                    'id' => 'site_email',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('site_email'),
                ]
            ],
            'options' => [
                'open' => 'open'
            ]
        ];

        $form['front_page'] = [
            'type' => 'details',
            'label' => 'Front page',
            'name' => 'front_page',
            'id' => 'front_page',
            'class' => ['form-details'],
            'handler' => DetailWrapperField::class,
            'inner_field' => [
                'front_page_url' => [
                    'label' => 'Front page url',
                    'type' => 'text',
                    'name' => 'front_page_url',
                    'id' => 'front_page_url',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('front_page_url'),
                ]
            ],
            'options' => [
                'open' => 'open'
            ]
        ];

        $form['error_pages'] = [
            'type' => 'details',
            'label' => 'Error pages',
            'name' => 'error_pages',
            'id' => 'error_pages',
            'class' => ['form-details'],
            'handler' => DetailWrapperField::class,
            'inner_field' => [
                'not_found_page' => [
                    'label' => 'Not found page',
                    'type' => 'text',
                    'required' => true,
                    'name' => 'not_found_page',
                    'id' => 'not_found_page',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('not_found_page'),
                ],
                'access_denied_page' => [
                    'label' => 'Access denied',
                    'type' => 'text',
                    'required' => true,
                    'name' => 'access_denied_page',
                    'id' => 'access_denied_page',
                    'class' => ['form-control'],
                    'default_value' => $config?->get('access_denied_page'),
                ]
            ]
        ];

        $form['submit'] = [
            'type' => 'submit',
            'name' => 'submit',
            'id' => 'submit',
            'class' => ['btn', 'btn-primary'],
            'default_value' => 'Submit',
        ];
        return $form;
    }

    public function validateForm(array $form): void
    {
        foreach ($form as $value) {
            if ($value instanceof FieldBase && $value->getRequired() === 'required' && empty($value->getValue())) {
                $this->validated = false;
            }
        }
    }

    public function submitForm(array $form): void
    {
        if ($this->validated) {
            unset($form['submit']);
            $basic_setting = array_map(fn($value) => $value->getValue(), $form);

            $settings = [
                ...$basic_setting['site'],
                ...$basic_setting['front_page'],
                ...$basic_setting['error_pages']
            ];

            ConfigManager::config()->addConfigFile('basic.site.setting', $settings);
            $redirect = new RedirectResponse('/admin/config/system/site-information');
            $redirect->send();
        }
    }
}